name: Bump CoreDNS Version in Release

on:
  schedule:
    - cron: "0 4 * * *"  # everyday at 4am

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: "Checkout"
      uses: actions/checkout@v2
    - id: meta
      name: "Version Bump"
      run: |
        pip3 install -r ./scripts/requirements.txt -q --no-input
        ./scripts/version-bump
    - id: release
      if: steps.meta.outputs.createRelease == 'true'
      name: "Create Release"
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.meta.outputs.vZeroDNS }}
        release_name: "Upgrade to CoreDNS: ${{ steps.meta.outputs.vCoreDNS }}"
        body: ${{ steps.meta.outputs.body }}
        prerelease: true